feat: Added addMetadata to token plugin
metaplex-foundation/js pull request #183
Opened 2022-07-22 07:12 UTC by stegaBOB

2022-07-22 09:34 UTC, lorisleiva requested changes
Thanks! I left some comments.

2022-07-22 09:34 UTC, lorisleiva commented on packages/js/src/plugins/tokenModule/TokenClient.ts
> +  ): Task<AddMetadataOutput & { mintWithMetadata: MintWithMetadata | Mint }> {
If you're adding metadata and you end up with a `Mint` model then something went wrong.

```suggestion
  ): Task<AddMetadataOutput & { mintWithMetadata: MintWithMetadata }> {
```

You can assert that `mintWithMetadata` is not a `Mint` model by using `assertMintWithMetadata(...)`.

2022-07-22 09:34 UTC, lorisleiva commented on packages/js/src/plugins/tokenModule/TokenClient.ts
> +  addMetadata(
As discussed on Slack, would you mind moving that operation to the NFT module instead?

2022-07-22 09:34 UTC, lorisleiva commented on packages/js/src/plugins/tokenModule/addMetadata.ts
> +  updateAuthority?: Signer; // Defaults to mx.identity().
Here the `updateAuthority` does not need to be a Signer.

```suggestion
  updateAuthority?: PublicKey; // Defaults to mx.identity().publicKey.
```

2022-07-22 09:34 UTC, lorisleiva commented on packages/js/src/plugins/tokenModule/addMetadata.ts
> +): Promise<TransactionBuilder<AddMetadataBuilderContext>> => {
There's no need for this builder method to be async.

2022-07-22 15:42 UTC, stegaBOB commented
Resolved all the comments!

2022-07-25 14:28 UTC, lorisleiva approved these changes

2022-07-25 14:28 UTC, merged

2022-07-25 14:28 UTC, lorisleiva commented
Thanks!