Add operations builders to AuctionHouseBuildersClient
metaplex-foundation/js pull request #283
Opened 2022-09-13 10:08 UTC by antey13

2022-09-13 10:10 UTC, zaxozhu approved these changes

2022-09-13 22:14 UTC, lorisleiva requested changes
Thanks! Can we please keep these methods ordered alphabetically?

This is because these methods are just registering transaction builders so it removes the need to think in what order we want them when we register them here.

2022-09-15 11:22 UTC, zaxozhu commented on packages/js/src/plugins/auctionHouseModule/AuctionHouseBuildersClient.ts
> +  /** {@inheritDoc cancelListingBuilder} */
New line here, please

2022-09-15 12:51 UTC, antey13 commented on packages/js/src/plugins/auctionHouseModule/AuctionHouseBuildersClient.ts
> +  /** {@inheritDoc cancelListingBuilder} */
done

2022-09-20 09:27 UTC, merged

2022-09-20 09:27 UTC, lorisleiva commented
Thanks!